name:                hfetch-weather
version:             0.1.0.0
github:              "githubuser/hfetch-weather"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hfetch-weather#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - StandaloneDeriving
  - TypeApplications
executables:
  hfetch-weather-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ld-options:
    - -pthread
    dependencies:
    - hfetch-weather
    - bytestring
    - http-conduit
    - aeson
    - lens
    - lens-aeson
    - text
    - either
    - transformers
    - directory
    - process
    - time
tests:
  hfetch-weather-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hfetch-weather
